kind: Build
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    openshift.io/build-config.name: nodejs-welcome
    openshift.io/build.number: '1'
    openshift.io/build.pod-name: nodejs-welcome-1-build
  name: nodejs-welcome-1
  namespace: welcome
  ownerReferences:
    - apiVersion: build.openshift.io/v1
      kind: BuildConfig
      name: nodejs-welcome
      controller: true
  labels:
    app: nodejs-welcome
    app.kubernetes.io/part-of: nodejs-welcome
    app.kubernetes.io/instance: nodejs-welcome
    openshift.io/build-config.name: nodejs-welcome
    app.kubernetes.io/component: nodejs-welcome
    openshift.io/build.start-policy: Serial
    buildconfig: nodejs-welcome
    app.openshift.io/runtime: nodejs
    app.kubernetes.io/name: nodejs
    app.openshift.io/runtime-version: '12'
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs-welcome:latest'
  resources: {}
        fromRef:
          kind: ImageStreamTag
          namespace: openshift
          name: 'nodejs:12'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: >-
          nodejs:12
  postCommit: {}
  serviceAccount: builder
  source:
    type: Git
    git:
      uri: 'https://github.com/samueltauil/nodejs-welcome.git'
    contextDir: /
  revision:
    type: Git
    git:
      commit: 521373dd2b211fe2442f666b16cbc6dfcc7e67e8
      author:
        name: Samuel Tauil
        email: samueltauil@gmail.com
      committer:
        name: Samuel Tauil
        email: samueltauil@gmail.com
      message: version change
status:

