kind: Build
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    openshift.io/build-config.name: nodejs-welcome
    openshift.io/build.number: '1'
    openshift.io/build.pod-name: nodejs-welcome-1-build
  name: nodejs-welcome-1
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: build.openshift.io/v1
  namespace: welcome
  ownerReferences:
    - apiVersion: build.openshift.io/v1
      kind: BuildConfig
      name: nodejs-welcome
      controller: true
  labels:
    app: nodejs-welcome
    app.kubernetes.io/part-of: nodejs-welcome
    app.kubernetes.io/instance: nodejs-welcome
    openshift.io/build-config.name: nodejs-welcome
    app.kubernetes.io/component: nodejs-welcome
    openshift.io/build.start-policy: Serial
    buildconfig: nodejs-welcome
    app.openshift.io/runtime: nodejs
    app.kubernetes.io/name: nodejs
    app.openshift.io/runtime-version: '12'
spec:
  serviceAccount: builder
  source:
    type: Git
    git:
      uri: 'https://github.com/samueltauil/nodejs-welcome.git'
    contextDir: /
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: >-
          image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:2bfd71b41a1591a1ea19513cb92e5c1f43d235bbdf15b114b8fddd5521e99482
      pullSecret:
        name: builder-dockercfg-nwf7w
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs-welcome:latest'
    pushSecret:
      name: builder-dockercfg-nwf7w
  resources: {}
  postCommit: {}
  nodeSelector: null
  triggeredBy:
    - message: Manually triggered
status:

