kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/samueltauil/nodejs-welcome.git'
  name: nodejs-welcome
  namespace: welcome
  labels:
    app: nodejs-welcome
    app.kubernetes.io/component: nodejs-welcome
    app.kubernetes.io/instance: nodejs-welcome
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: nodejs-welcome
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: '12'
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'nodejs-welcome:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:12'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/samueltauil/nodejs-welcome.git'
    contextDir: /
  runPolicy: Serial

