apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nodejs-welcome            
  namespace: welcome               
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      app : nodejs-welcome
