apiVersion: v1 
kind: Namespace
metadata:
  name: welcome
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: nodejs-welcome
  namespace: welcome
spec:
  type: Git
  pathname: https://github.com/samueltauil/nodejs-welcome.git
