apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: clusterselection
  namespace: welcome
  labels:
    app: nodejs-welcome
spec:
  clusterReplicas: 1
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchExpressions:
    - key: environment
      operator: In
      values:
      - dev
