apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-path: resources
  name: welcome-subscription                             
  namespace: welcome                       
  labels:
    app : nodejs-welcome
spec:
  channel: welcome/nodejs-welcome                 
  placement: 
    placementRef: 
      kind: PlacementRule
      name: clusterselection 
